# Generated by Django 5.2.6 on 2026-09-02 06:22

import apps.brainstorm.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prds', '0003_prd_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrainstormCanvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prd', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brainstorm_canvas', to='prds.prd')),
            ],
            options={
                'db_table': 'brainstorm_canvases',
            },
        ),
        migrations.CreateModel(
            name='BrainstormNode',
            fields=[
                ('id', models.UUIDField(db_default=apps.brainstorm.models.DatabaseRandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('node_type', models.CharField(choices=[('note', '일반 메모'), ('title', '제목 카드')], default='note', max_length=16)),
                ('content', models.TextField()),
                ('color', models.CharField(max_length=32)),
                ('position_x', models.DecimalField(decimal_places=3, max_digits=12)),
                ('position_y', models.DecimalField(decimal_places=3, max_digits=12)),
                ('author_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('assignee_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('default', '기본'), ('accepted', '채택'), ('held', '보류')], max_length=16, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='brainstorm.brainstormcanvas')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brainstorm_nodes', to='prds.prdsection')),
            ],
            options={
                'db_table': 'brainstorm_nodes',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BrainstormConnection',
            fields=[
                ('id', models.UUIDField(db_default=apps.brainstorm.models.DatabaseRandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='brainstorm.brainstormcanvas')),
                ('node_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_as_a', to='brainstorm.brainstormnode')),
                ('node_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_as_b', to='brainstorm.brainstormnode')),
            ],
            options={
                'db_table': 'brainstorm_connections',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserCanvasViewport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField()),
                ('viewport_x', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('viewport_y', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('zoom_level', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_viewports', to='brainstorm.brainstormcanvas')),
            ],
            options={
                'db_table': 'brainstorm_user_viewports',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_user_id', models.PositiveBigIntegerField()),
                ('action', models.CharField(max_length=64)),
                ('target_type', models.CharField(choices=[('canvas', '캔버스'), ('node', '노드'), ('connection', '연결선')], max_length=16)),
                ('target_id', models.CharField(max_length=64)),
                ('reason', models.CharField(blank=True, max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='brainstorm.brainstormcanvas')),
            ],
            options={
                'db_table': 'brainstorm_audit_logs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['canvas', '-created_at'], name='brain_audit_created_idx'), models.Index(fields=['reason', '-created_at'], name='brain_audit_reason_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('actor_user_id__gt', 0)), name='brain_audit_actor_positive'), models.CheckConstraint(condition=models.Q(('target_type__in', ['canvas', 'node', 'connection'])), name='brain_audit_target_valid'), models.CheckConstraint(condition=models.Q(('action', ''), _negated=True), name='brain_audit_action_not_blank'), models.CheckConstraint(condition=models.Q(('target_id', ''), _negated=True), name='brain_audit_target_not_blank')],
            },
        ),
        migrations.CreateModel(
            name='BrainstormChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_user_id', models.PositiveBigIntegerField()),
                ('operation_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('action', models.CharField(max_length=64)),
                ('target_type', models.CharField(choices=[('canvas', '캔버스'), ('node', '노드'), ('connection', '연결선')], max_length=16)),
                ('target_id', models.CharField(max_length=64)),
                ('before_data', models.JSONField(blank=True, default=dict)),
                ('after_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='brainstorm.brainstormcanvas')),
            ],
            options={
                'db_table': 'brainstorm_change_logs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['canvas', '-id'], name='brain_change_poll_idx'), models.Index(fields=['operation_id'], name='brain_change_operation_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('actor_user_id__gt', 0)), name='brain_change_actor_positive'), models.CheckConstraint(condition=models.Q(('target_type__in', ['canvas', 'node', 'connection'])), name='brain_change_target_valid'), models.CheckConstraint(condition=models.Q(('action', ''), _negated=True), name='brain_change_action_not_blank'), models.CheckConstraint(condition=models.Q(('target_id', ''), _negated=True), name='brain_change_target_not_blank')],
            },
        ),
        migrations.AddIndex(
            model_name='brainstormnode',
            index=models.Index(fields=['canvas', 'is_deleted', 'node_type', 'status'], name='brain_node_canvas_state_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormnode',
            index=models.Index(fields=['canvas', 'section', 'is_deleted'], name='brain_node_section_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormnode',
            index=models.Index(fields=['canvas', 'assignee_id', 'is_deleted'], name='brain_node_assignee_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormnode',
            index=models.Index(fields=['deleted_at'], name='brain_node_deleted_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='brainstormnode',
            constraint=models.CheckConstraint(condition=models.Q(('node_type__in', ['note', 'title'])), name='brain_node_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='brainstormnode',
            constraint=models.CheckConstraint(condition=models.Q(('status__isnull', True), ('status__in', ['default', 'accepted', 'held']), _connector='OR'), name='brain_node_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='brainstormnode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('author_id__isnull', False), ('node_type', 'note'), ('status__in', ['default', 'accepted', 'held'])), models.Q(('assignee_id__isnull', True), ('author_id__isnull', True), ('node_type', 'title'), ('status__isnull', True)), _connector='OR'), name='brain_node_type_fields_valid'),
        ),
        migrations.AddConstraint(
            model_name='brainstormnode',
            constraint=models.CheckConstraint(condition=models.Q(('author_id__isnull', True), ('author_id__gt', 0), _connector='OR'), name='brain_node_author_positive'),
        ),
        migrations.AddConstraint(
            model_name='brainstormnode',
            constraint=models.CheckConstraint(condition=models.Q(('assignee_id__isnull', True), ('assignee_id__gt', 0), _connector='OR'), name='brain_node_assignee_positive'),
        ),
        migrations.AddConstraint(
            model_name='brainstormnode',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='brain_node_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='brainstormnode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'held'), _negated=True), ('section__isnull', True), _connector='OR'), name='brain_held_node_unclassified'),
        ),
        migrations.AddConstraint(
            model_name='brainstormnode',
            constraint=models.CheckConstraint(condition=models.Q(('content', ''), _negated=True), name='brain_node_content_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='brainstormnode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deleted_at__isnull', True), ('is_deleted', False)), models.Q(('deleted_at__isnull', False), ('is_deleted', True)), _connector='OR'), name='brain_node_deleted_consistent'),
        ),
        migrations.AddIndex(
            model_name='brainstormconnection',
            index=models.Index(fields=['canvas', 'is_deleted', 'updated_at'], name='brain_conn_poll_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormconnection',
            index=models.Index(fields=['node_a', 'is_deleted'], name='brain_conn_node_a_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormconnection',
            index=models.Index(fields=['node_b', 'is_deleted'], name='brain_conn_node_b_idx'),
        ),
        migrations.AddConstraint(
            model_name='brainstormconnection',
            constraint=models.UniqueConstraint(fields=('canvas', 'node_a', 'node_b'), name='uniq_brain_connection_nodes'),
        ),
        migrations.AddConstraint(
            model_name='brainstormconnection',
            constraint=models.CheckConstraint(condition=models.Q(('node_a', models.F('node_b')), _negated=True), name='brain_connection_not_self'),
        ),
        migrations.AddConstraint(
            model_name='brainstormconnection',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='brain_connection_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='brainstormconnection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deleted_at__isnull', True), ('is_deleted', False)), models.Q(('deleted_at__isnull', False), ('is_deleted', True)), _connector='OR'), name='brain_connection_deleted_consistent'),
        ),
        migrations.AddConstraint(
            model_name='usercanvasviewport',
            constraint=models.UniqueConstraint(fields=('canvas', 'user_id'), name='uniq_brain_viewport_user'),
        ),
        migrations.AddConstraint(
            model_name='usercanvasviewport',
            constraint=models.CheckConstraint(condition=models.Q(('user_id__gt', 0)), name='brain_viewport_user_positive'),
        ),
        migrations.AddConstraint(
            model_name='usercanvasviewport',
            constraint=models.CheckConstraint(condition=models.Q(('zoom_level__gte', Decimal('0.30')), ('zoom_level__lte', Decimal('2.00'))), name='brain_viewport_zoom_range'),
        ),
    ]
