# Generated by Django 5.2.6 on 2026-09-02 06:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainstorm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='brainstormconnection',
            name='uniq_brain_connection_nodes',
        ),
        migrations.AddField(
            model_name='brainstormconnection',
            name='creation_idempotency_key',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=128),
        ),
        migrations.AddConstraint(
            model_name='brainstormconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('canvas', 'node_a', 'node_b'), name='uniq_brain_connection_nodes'),
        ),
        migrations.AddConstraint(
            model_name='brainstormconnection',
            constraint=models.UniqueConstraint(fields=('canvas', 'creation_idempotency_key'), name='uniq_brain_connection_request'),
        ),
        migrations.AddConstraint(
            model_name='brainstormconnection',
            constraint=models.CheckConstraint(condition=models.Q(('creation_idempotency_key', ''), _negated=True), name='brain_connection_key_not_blank'),
        ),
    ]
