# Generated by Django 5.2.6 on 2026-09-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainstorm', '0002_remove_brainstormconnection_uniq_brain_connection_nodes_and_more'),
        ('prds', '0006_prd_contribution_status_prd_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brainstormcanvas',
            name='creation_idempotency_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='brainstormnode',
            name='creation_idempotency_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddConstraint(
            model_name='brainstormnode',
            constraint=models.UniqueConstraint(condition=models.Q(('creation_idempotency_key', ''), _negated=True), fields=('canvas', 'author_id', 'creation_idempotency_key'), name='uniq_brain_node_request'),
        ),
    ]
