# Generated by Django 5.2.6 on 2026-09-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PrdTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prd_type",
                    models.CharField(
                        choices=[
                            ("new_product", "신규 프로젝트"),
                            ("new_feature", "신규 기능"),
                            ("improvement", "기능 개선"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "prd_templates",
                "ordering": ["prd_type"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            prd_type__in=["new_product", "new_feature", "improvement"]
                        ),
                        name="prd_template_type_valid",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Prd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("deadline", models.DateField(blank=True, null=True)),
                (
                    "prd_type",
                    models.CharField(
                        choices=[
                            ("new_product", "신규 프로젝트"),
                            ("new_feature", "신규 기능"),
                            ("improvement", "기능 개선"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "작성 중"),
                            ("completed", "완료"),
                            ("held", "보류"),
                            ("dropped", "드랍"),
                        ],
                        default="in_progress",
                        max_length=32,
                    ),
                ),
                ("round_id", models.PositiveBigIntegerField()),
                ("team_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("creator_user_id", models.PositiveBigIntegerField()),
                ("creation_idempotency_key", models.CharField(max_length=128)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "prds",
                "indexes": [
                    models.Index(
                        fields=["status", "-updated_at"], name="prd_status_updated_idx"
                    ),
                    models.Index(
                        fields=["prd_type", "-updated_at"], name="prd_type_updated_idx"
                    ),
                    models.Index(fields=["deadline"], name="prd_deadline_idx"),
                    models.Index(fields=["round_id", "team_id"], name="prd_round_team_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            prd_type__in=["new_product", "new_feature", "improvement"]
                        ),
                        name="prd_type_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            status__in=["in_progress", "completed", "held", "dropped"]
                        ),
                        name="prd_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(round_id__gt=0),
                        name="prd_round_id_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(creator_user_id__gt=0),
                        name="prd_creator_user_id_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(team_id__isnull=True)
                        | models.Q(team_id__gt=0),
                        name="prd_team_id_null_or_positive",
                    ),
                    models.CheckConstraint(
                        condition=~models.Q(creation_idempotency_key=""),
                        name="prd_idempotency_key_not_blank",
                    ),
                    models.UniqueConstraint(
                        fields=("creator_user_id", "round_id", "creation_idempotency_key"),
                        name="uniq_prd_creation_request",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("deleted_at__isnull", True), ("is_deleted", False)),
                            models.Q(("deleted_at__isnull", False), ("is_deleted", True)),
                            _connector="OR",
                        ),
                        name="prd_deleted_fields_consistent",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PrdTemplateSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("guide", models.TextField(blank=True)),
                ("position", models.PositiveIntegerField()),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="prds.prdtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "prd_template_sections",
                "ordering": ["position", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("template", "position"),
                        name="uniq_prd_template_section_position",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PrdTemplateQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField()),
                ("position", models.PositiveIntegerField()),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="prds.prdtemplatesection",
                    ),
                ),
            ],
            options={
                "db_table": "prd_template_questions",
                "ordering": ["position", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("section", "position"),
                        name="uniq_prd_template_question_position",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PrdSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("guide", models.TextField(blank=True)),
                ("position", models.PositiveIntegerField()),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="prds.prd",
                    ),
                ),
            ],
            options={
                "db_table": "prd_sections",
                "ordering": ["position", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("prd", "position"), name="uniq_prd_section_position"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("deleted_at__isnull", True), ("is_deleted", False)),
                            models.Q(("deleted_at__isnull", False), ("is_deleted", True)),
                            _connector="OR",
                        ),
                        name="prd_section_deleted_fields_consistent",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PrdQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField()),
                ("position", models.PositiveIntegerField()),
                ("is_completed", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="prds.prdsection",
                    ),
                ),
            ],
            options={
                "db_table": "prd_questions",
                "ordering": ["position", "id"],
                "indexes": [
                    models.Index(
                        fields=["section", "is_deleted", "is_completed"],
                        name="prd_question_completion_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("section", "position"), name="uniq_prd_question_position"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("deleted_at__isnull", True), ("is_deleted", False)),
                            models.Q(("deleted_at__isnull", False), ("is_deleted", True)),
                            _connector="OR",
                        ),
                        name="prd_question_deleted_fields_consistent",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PrdAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("updated_by_user_id", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer",
                        to="prds.prdquestion",
                    ),
                ),
            ],
            options={"db_table": "prd_answers"},
        ),
        migrations.CreateModel(
            name="PrdChangeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_user_id", models.PositiveBigIntegerField()),
                ("event_type", models.CharField(max_length=64)),
                ("before_data", models.JSONField(blank=True, default=dict)),
                ("after_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_history",
                        to="prds.prd",
                    ),
                ),
            ],
            options={
                "db_table": "prd_change_history",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["prd", "-created_at"], name="prd_history_created_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PrdParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.PositiveBigIntegerField()),
                ("participant_id", models.PositiveBigIntegerField()),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "소유자"),
                            ("editor", "편집자"),
                            ("tutor", "튜터"),
                            ("viewer", "열람자"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="prds.prd",
                    ),
                ),
            ],
            options={
                "db_table": "prd_participants",
                "indexes": [
                    models.Index(
                        fields=["user_id", "prd"], name="prd_part_user_prd_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(user_id__gt=0),
                        name="prd_participant_user_id_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(participant_id__gt=0),
                        name="prd_participant_external_id_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(role__in=["owner", "editor", "tutor", "viewer"]),
                        name="prd_participant_role_valid",
                    ),
                    models.UniqueConstraint(
                        fields=("prd", "user_id"), name="uniq_prd_participant_user"
                    ),
                    models.UniqueConstraint(
                        fields=("prd", "participant_id"),
                        name="uniq_prd_participant_external",
                    ),
                ],
            },
        ),
    ]
