# Generated by Django 5.2.6 on 2026-09-02 11:41

import django.db.models.deletion
from django.db import migrations, models


def backfill_completed_at(apps, schema_editor):
    prd_model = apps.get_model("prds", "Prd")
    prd_model.objects.filter(status="completed", completed_at__isnull=True).update(
        completed_at=models.F("updated_at")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("prds", "0004_prdquestion_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prd",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_completed_at, migrations.RunPython.noop),
        migrations.CreateModel(
            name="PrdStatusAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("actor_user_id", models.PositiveBigIntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[("completed", "완료"), ("reopened", "재개")], max_length=16
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        choices=[
                            ("in_progress", "작성 중"),
                            ("completed", "완료"),
                            ("held", "보류"),
                            ("dropped", "드랍"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("in_progress", "작성 중"),
                            ("completed", "완료"),
                            ("held", "보류"),
                            ("dropped", "드랍"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("previous_completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_audit_logs",
                        to="prds.prd",
                    ),
                ),
            ],
            options={
                "db_table": "prd_status_audit_logs",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["prd", "-created_at"], name="prd_status_audit_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("actor_user_id__gt", 0)),
                        name="prd_status_audit_actor_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("action__in", ["completed", "reopened"])),
                        name="prd_status_audit_action_valid",
                    ),
                ],
            },
        ),
    ]
