# Generated by Django 5.2.6 on 2026-09-02 06:50

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aichathistory'),
        ('prds', '0003_prd_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.PositiveBigIntegerField()),
                ('feature_type', models.CharField(choices=[('BRAINSTORM_ANALYSIS', '브레인스토밍 분석'), ('BRAINSTORM_CLASSIFICATION', '브레인스토밍 분류'), ('BRAINSTORM_PRD_APPLY', '브레인스토밍 PRD 반영'), ('CONTRIBUTION_EVALUATION', '기여도 평가'), ('COACHING', 'AI 코칭')], max_length=32)),
                ('action_type', models.CharField(choices=[('analysis', '분석'), ('classification', '분류'), ('prd_apply', 'PRD 반영'), ('contribution_evaluation', '기여도 평가'), ('chat', '대화'), ('draft', '초안')], max_length=32)),
                ('status', models.CharField(choices=[('queued', '대기'), ('running', '실행 중'), ('retry_wait', '재시도 대기'), ('cancel_requested', '취소 요청'), ('succeeded', '성공'), ('failed', '실패'), ('cancelled', '취소됨'), ('timed_out', '시간 초과')], default='queued', max_length=24)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('input_data', models.JSONField(default=dict)),
                ('output_data', models.JSONField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, max_length=128)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_jobs',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AiPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(choices=[('BRAINSTORM_ANALYSIS', '브레인스토밍 분석'), ('BRAINSTORM_CLASSIFICATION', '브레인스토밍 분류'), ('BRAINSTORM_PRD_APPLY', '브레인스토밍 PRD 반영'), ('CONTRIBUTION_EVALUATION', '기여도 평가'), ('COACHING', 'AI 코칭')], max_length=32)),
                ('version', models.PositiveIntegerField()),
                ('system_instructions', models.TextField()),
                ('output_schema', models.JSONField(default=dict)),
                ('model', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_prompts',
                'ordering': ['feature_type', '-version'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='aiusagelog',
            name='ai_usage_feature_type_valid',
        ),
        migrations.RemoveConstraint(
            model_name='aiusagelog',
            name='ai_usage_action_type_valid',
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='cost_usd',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='error_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='input_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='model',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='output_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='prompt_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='action_type',
            field=models.CharField(choices=[('analysis', '분석'), ('classification', '분류'), ('prd_apply', 'PRD 반영'), ('contribution_evaluation', '기여도 평가'), ('chat', '대화'), ('draft', '초안')], max_length=32),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='feature_type',
            field=models.CharField(choices=[('BRAINSTORM_ANALYSIS', '브레인스토밍 분석'), ('BRAINSTORM_CLASSIFICATION', '브레인스토밍 분류'), ('BRAINSTORM_PRD_APPLY', '브레인스토밍 PRD 반영'), ('CONTRIBUTION_EVALUATION', '기여도 평가'), ('COACHING', 'AI 코칭')], max_length=32),
        ),
        migrations.AddField(
            model_name='aijob',
            name='prd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to='prds.prd'),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='ai.aijob'),
        ),
        migrations.AddIndex(
            model_name='aiusagelog',
            index=models.Index(fields=['user_id', 'feature_type', '-created_at'], name='ai_usage_limit_idx'),
        ),
        migrations.AddConstraint(
            model_name='aiusagelog',
            constraint=models.CheckConstraint(condition=models.Q(('feature_type__in', ['BRAINSTORM_ANALYSIS', 'BRAINSTORM_CLASSIFICATION', 'BRAINSTORM_PRD_APPLY', 'CONTRIBUTION_EVALUATION', 'COACHING'])), name='ai_usage_feature_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='aiusagelog',
            constraint=models.CheckConstraint(condition=models.Q(('action_type__in', ['analysis', 'classification', 'prd_apply', 'contribution_evaluation', 'chat', 'draft'])), name='ai_usage_action_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='aiusagelog',
            constraint=models.CheckConstraint(condition=models.Q(('total_tokens__gte', django.db.models.expressions.CombinedExpression(models.F('input_tokens'), '+', models.F('output_tokens')))), name='ai_usage_token_total_valid'),
        ),
        migrations.AddConstraint(
            model_name='aiusagelog',
            constraint=models.CheckConstraint(condition=models.Q(('cost_usd__gte', 0)), name='ai_usage_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='aiusagelog',
            constraint=models.CheckConstraint(condition=models.Q(('prompt_version__gte', 1)), name='ai_usage_prompt_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='aiusagelog',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_number__gte', 1)), name='ai_usage_attempt_positive'),
        ),
        migrations.AddConstraint(
            model_name='aiusagelog',
            constraint=models.CheckConstraint(condition=models.Q(('model', ''), _negated=True), name='ai_usage_model_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='aiprompt',
            constraint=models.UniqueConstraint(fields=('feature_type', 'version'), name='uniq_ai_prompt_feature_version'),
        ),
        migrations.AddConstraint(
            model_name='aiprompt',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('feature_type',), name='uniq_active_ai_prompt_feature'),
        ),
        migrations.AddConstraint(
            model_name='aiprompt',
            constraint=models.CheckConstraint(condition=models.Q(('feature_type__in', ['BRAINSTORM_ANALYSIS', 'BRAINSTORM_CLASSIFICATION', 'BRAINSTORM_PRD_APPLY', 'CONTRIBUTION_EVALUATION', 'COACHING'])), name='ai_prompt_feature_valid'),
        ),
        migrations.AddConstraint(
            model_name='aiprompt',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='ai_prompt_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='aiprompt',
            constraint=models.CheckConstraint(condition=models.Q(('system_instructions', ''), _negated=True), name='ai_prompt_system_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='aiprompt',
            constraint=models.CheckConstraint(condition=models.Q(('model', ''), _negated=True), name='ai_prompt_model_not_blank'),
        ),
        migrations.AddField(
            model_name='aijob',
            name='prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='ai.aiprompt'),
        ),
        migrations.AddIndex(
            model_name='aijob',
            index=models.Index(fields=['status', 'available_at', 'created_at'], name='ai_job_claim_idx'),
        ),
        migrations.AddIndex(
            model_name='aijob',
            index=models.Index(fields=['status', 'lease_expires_at'], name='ai_job_lease_idx'),
        ),
        migrations.AddIndex(
            model_name='aijob',
            index=models.Index(fields=['user_id', 'feature_type', '-created_at'], name='ai_job_user_limit_idx'),
        ),
        migrations.AddConstraint(
            model_name='aijob',
            constraint=models.UniqueConstraint(fields=('user_id', 'prd', 'feature_type', 'idempotency_key'), name='uniq_ai_job_request'),
        ),
        migrations.AddConstraint(
            model_name='aijob',
            constraint=models.CheckConstraint(condition=models.Q(('user_id__gt', 0)), name='ai_job_user_positive'),
        ),
        migrations.AddConstraint(
            model_name='aijob',
            constraint=models.CheckConstraint(condition=models.Q(('feature_type__in', ['BRAINSTORM_ANALYSIS', 'BRAINSTORM_CLASSIFICATION', 'BRAINSTORM_PRD_APPLY', 'CONTRIBUTION_EVALUATION', 'COACHING'])), name='ai_job_feature_valid'),
        ),
        migrations.AddConstraint(
            model_name='aijob',
            constraint=models.CheckConstraint(condition=models.Q(('action_type__in', ['analysis', 'classification', 'prd_apply', 'contribution_evaluation', 'chat', 'draft'])), name='ai_job_action_valid'),
        ),
        migrations.AddConstraint(
            model_name='aijob',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['queued', 'running', 'retry_wait', 'cancel_requested', 'succeeded', 'failed', 'cancelled', 'timed_out'])), name='ai_job_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='aijob',
            constraint=models.CheckConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), name='ai_job_key_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='aijob',
            constraint=models.CheckConstraint(condition=models.Q(('max_attempts__gte', 1)), name='ai_job_max_attempts_positive'),
        ),
        migrations.AddConstraint(
            model_name='aijob',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_count__lte', models.F('max_attempts'))), name='ai_job_attempts_within_limit'),
        ),
        migrations.AddConstraint(
            model_name='aijob',
            constraint=models.CheckConstraint(condition=models.Q(('timeout_seconds__gte', 1)), name='ai_job_timeout_positive'),
        ),
    ]
