# Generated by Django 5.2.6 on 2026-09-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_aijob_aiprompt_and_more'),
        ('prds', '0003_prd_comments'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='aijob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action_type', 'analysis'), ('feature_type', 'BRAINSTORM_ANALYSIS')), models.Q(('action_type', 'classification'), ('feature_type', 'BRAINSTORM_CLASSIFICATION')), models.Q(('action_type', 'prd_apply'), ('feature_type', 'BRAINSTORM_PRD_APPLY')), models.Q(('action_type', 'contribution_evaluation'), ('feature_type', 'CONTRIBUTION_EVALUATION')), models.Q(('action_type__in', ['chat', 'draft']), ('feature_type', 'COACHING')), _connector='OR'), name='ai_job_feature_action_valid'),
        ),
        migrations.AddConstraint(
            model_name='aiusagelog',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action_type', 'analysis'), ('feature_type', 'BRAINSTORM_ANALYSIS')), models.Q(('action_type', 'classification'), ('feature_type', 'BRAINSTORM_CLASSIFICATION')), models.Q(('action_type', 'prd_apply'), ('feature_type', 'BRAINSTORM_PRD_APPLY')), models.Q(('action_type', 'contribution_evaluation'), ('feature_type', 'CONTRIBUTION_EVALUATION')), models.Q(('action_type__in', ['chat', 'draft']), ('feature_type', 'COACHING')), _connector='OR'), name='ai_usage_feature_action_valid'),
        ),
    ]
