# Generated by Django 5.2.6 on 2026-09-02 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_aijob_ai_job_feature_action_valid_and_more'),
        ('prds', '0004_prdquestion_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiCoachConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_coach_conversations', to='prds.prd')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_coach_conversations', to='prds.prdsection')),
            ],
            options={
                'db_table': 'ai_coach_conversations',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AiCoachMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveBigIntegerField()),
                ('role', models.CharField(choices=[('user', '사용자'), ('assistant', 'AI 코치')], max_length=16)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.aicoachconversation')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_messages', to='ai.aijob')),
            ],
            options={
                'db_table': 'ai_coach_messages',
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='aicoachconversation',
            index=models.Index(fields=['expires_at'], name='ai_coach_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='aicoachconversation',
            index=models.Index(fields=['prd', 'user_id'], name='ai_coach_prd_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='aicoachconversation',
            constraint=models.UniqueConstraint(condition=models.Q(('section__isnull', False)), fields=('prd', 'section', 'user_id'), name='uniq_ai_coach_section_user'),
        ),
        migrations.AddConstraint(
            model_name='aicoachconversation',
            constraint=models.UniqueConstraint(condition=models.Q(('section__isnull', True)), fields=('prd', 'user_id'), name='uniq_ai_coach_whole_user'),
        ),
        migrations.AddConstraint(
            model_name='aicoachconversation',
            constraint=models.CheckConstraint(condition=models.Q(('user_id__gt', 0)), name='ai_coach_user_positive'),
        ),
        migrations.AddIndex(
            model_name='aicoachmessage',
            index=models.Index(fields=['conversation', 'role', '-sequence'], name='ai_coach_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='aicoachmessage',
            constraint=models.UniqueConstraint(fields=('conversation', 'sequence'), name='uniq_ai_coach_message_sequence'),
        ),
        migrations.AddConstraint(
            model_name='aicoachmessage',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 1)), name='ai_coach_message_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='aicoachmessage',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['user', 'assistant'])), name='ai_coach_message_role_valid'),
        ),
        migrations.AddConstraint(
            model_name='aicoachmessage',
            constraint=models.CheckConstraint(condition=models.Q(('content', ''), _negated=True), name='ai_coach_message_content_not_blank'),
        ),
    ]
