# Generated by Django 5.2.6 on 2026-09-02 11:35

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0005_aicoachconversation_aicoachmessage_and_more"),
        ("brainstorm", "0002_remove_brainstormconnection_uniq_brain_connection_nodes_and_more"),
        ("prds", "0004_prdquestion_version_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiPrdApplyRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("section", "섹션"), ("all", "전체 PRD")], max_length=16
                    ),
                ),
                ("actor_user_id", models.PositiveBigIntegerField()),
                ("idempotency_key", models.CharField(max_length=128)),
                ("model", models.CharField(max_length=128)),
                ("prompt_version", models.PositiveIntegerField()),
                ("unused_node_ids", models.JSONField(default=list)),
                ("warnings", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "canvas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prd_apply_records",
                        to="brainstorm.brainstormcanvas",
                    ),
                ),
                (
                    "prd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_prd_apply_records",
                        to="prds.prd",
                    ),
                ),
                (
                    "preview_job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prd_apply_record",
                        to="ai.aijob",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_prd_apply_records",
                        to="prds.prdsection",
                    ),
                ),
            ],
            options={
                "db_table": "ai_prd_apply_records",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AiPrdApplyItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("question_version_before", models.PositiveBigIntegerField()),
                ("question_prompt", models.TextField()),
                ("existing_answer", models.TextField(blank=True)),
                ("integrated_answer", models.TextField()),
                ("source_nodes", models.JSONField(default=list)),
                ("preserved_existing_points", models.JSONField(default=list)),
                ("added_points", models.JSONField(default=list)),
                ("confidence", models.DecimalField(decimal_places=4, max_digits=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_prd_apply_items",
                        to="prds.prdquestion",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ai.aiprdapplyrecord",
                    ),
                ),
            ],
            options={
                "db_table": "ai_prd_apply_items",
                "ordering": ["question_id", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="aiprdapplyrecord",
            index=models.Index(fields=["prd", "-created_at"], name="ai_apply_prd_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="aiprdapplyrecord",
            constraint=models.UniqueConstraint(
                fields=("prd", "actor_user_id", "idempotency_key"), name="uniq_ai_prd_apply_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="aiprdapplyrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("scope__in", ["section", "all"])),
                name="ai_prd_apply_scope_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiprdapplyrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("scope", "section"), ("section__isnull", False)),
                    models.Q(("scope", "all"), ("section__isnull", True)),
                    _connector="OR",
                ),
                name="ai_prd_apply_scope_section_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiprdapplyrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("actor_user_id__gt", 0)), name="ai_prd_apply_actor_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="aiprdapplyrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("prompt_version__gte", 1)),
                name="ai_prd_apply_prompt_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiprdapplyrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                name="ai_prd_apply_key_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiprdapplyrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("model", ""), _negated=True),
                name="ai_prd_apply_model_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiprdapplyitem",
            constraint=models.UniqueConstraint(
                fields=("record", "question"), name="uniq_ai_prd_apply_item_question"
            ),
        ),
        migrations.AddConstraint(
            model_name="aiprdapplyitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("question_version_before__gte", 1)),
                name="ai_prd_apply_question_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiprdapplyitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("question_prompt", ""), _negated=True),
                name="ai_prd_apply_question_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiprdapplyitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("confidence__gte", Decimal("0")), ("confidence__lte", Decimal("1"))
                ),
                name="ai_prd_apply_confidence_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiprdapplyitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("integrated_answer", ""), _negated=True),
                name="ai_prd_apply_answer_not_blank",
            ),
        ),
    ]
