# Generated by Django 5.2.6 on 2026-09-02 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_aiprdapplyrecord_aiprdapplyitem_and_more'),
        ('prds', '0006_prd_contribution_status_prd_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_version', models.PositiveIntegerField()),
                ('prd_version', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('pending', '계산 중'), ('succeeded', '완료'), ('failed', '실패')], default='pending', max_length=16)),
                ('input_fingerprint', models.CharField(max_length=64)),
                ('input_snapshot', models.JSONField(default=dict)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('prompt_version', models.PositiveIntegerField(blank=True, null=True)),
                ('target_node_ids', models.JSONField(default=list)),
                ('target_comment_ids', models.JSONField(default=list)),
                ('evidence', models.JSONField(default=dict)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('failure_message', models.TextField(blank=True)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completion_audit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contribution_evaluation', to='prds.prdstatusauditlog')),
                ('job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution_evaluation', to='ai.aijob')),
                ('prd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_evaluations', to='prds.prd')),
            ],
            options={
                'db_table': 'contribution_evaluations',
                'ordering': ['prd', 'calculation_version'],
            },
        ),
        migrations.CreateModel(
            name='ContributionCommentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_user_id', models.PositiveBigIntegerField()),
                ('reflection_score', models.DecimalField(decimal_places=4, max_digits=7)),
                ('matched_question_ids', models.JSONField(default=list)),
                ('evidence', models.JSONField(default=list)),
                ('reason', models.TextField()),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contribution_scores', to='prds.prdcomment')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_scores', to='ai.contributionevaluation')),
            ],
            options={
                'db_table': 'contribution_comment_scores',
                'ordering': ['evaluation', 'comment_id'],
            },
        ),
        migrations.CreateModel(
            name='ContributionUserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField()),
                ('participant_id', models.PositiveBigIntegerField()),
                ('memo_raw', models.PositiveIntegerField(default=0)),
                ('memo_contribution', models.DecimalField(decimal_places=4, max_digits=7)),
                ('comment_raw', models.DecimalField(decimal_places=4, max_digits=12)),
                ('comment_contribution', models.DecimalField(decimal_places=4, max_digits=7)),
                ('total_score', models.DecimalField(decimal_places=4, max_digits=7)),
                ('node_ids', models.JSONField(default=list)),
                ('comment_ids', models.JSONField(default=list)),
                ('evidence', models.JSONField(default=dict)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scores', to='ai.contributionevaluation')),
            ],
            options={
                'db_table': 'contribution_user_scores',
                'ordering': ['evaluation', 'user_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='contributionevaluation',
            constraint=models.UniqueConstraint(fields=('prd', 'calculation_version'), name='uniq_contribution_calculation_version'),
        ),
        migrations.AddConstraint(
            model_name='contributionevaluation',
            constraint=models.CheckConstraint(condition=models.Q(('calculation_version__gte', 1)), name='contribution_calculation_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='contributionevaluation',
            constraint=models.CheckConstraint(condition=models.Q(('prd_version__gte', 1)), name='contribution_prd_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='contributionevaluation',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'succeeded', 'failed'])), name='contribution_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='contributionevaluation',
            constraint=models.CheckConstraint(condition=models.Q(('input_fingerprint', ''), _negated=True), name='contribution_fingerprint_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='contributioncommentscore',
            constraint=models.UniqueConstraint(fields=('evaluation', 'comment'), name='uniq_contribution_comment_score'),
        ),
        migrations.AddConstraint(
            model_name='contributioncommentscore',
            constraint=models.CheckConstraint(condition=models.Q(('author_user_id__gt', 0)), name='contribution_comment_author_positive'),
        ),
        migrations.AddConstraint(
            model_name='contributioncommentscore',
            constraint=models.CheckConstraint(condition=models.Q(('reflection_score__gte', 0), ('reflection_score__lte', 100)), name='contribution_reflection_score_range'),
        ),
        migrations.AddConstraint(
            model_name='contributioncommentscore',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='contribution_confidence_range'),
        ),
        migrations.AddConstraint(
            model_name='contributionuserscore',
            constraint=models.UniqueConstraint(fields=('evaluation', 'user_id'), name='uniq_contribution_user_score'),
        ),
        migrations.AddConstraint(
            model_name='contributionuserscore',
            constraint=models.CheckConstraint(condition=models.Q(('user_id__gt', 0)), name='contribution_user_positive'),
        ),
        migrations.AddConstraint(
            model_name='contributionuserscore',
            constraint=models.CheckConstraint(condition=models.Q(('participant_id__gt', 0)), name='contribution_participant_positive'),
        ),
        migrations.AddConstraint(
            model_name='contributionuserscore',
            constraint=models.CheckConstraint(condition=models.Q(('memo_contribution__gte', 0), ('memo_contribution__lte', 100)), name='contribution_memo_score_range'),
        ),
        migrations.AddConstraint(
            model_name='contributionuserscore',
            constraint=models.CheckConstraint(condition=models.Q(('comment_contribution__gte', 0), ('comment_contribution__lte', 100)), name='contribution_comment_score_range'),
        ),
        migrations.AddConstraint(
            model_name='contributionuserscore',
            constraint=models.CheckConstraint(condition=models.Q(('total_score__gte', 0), ('total_score__lte', 100)), name='contribution_total_score_range'),
        ),
    ]
