# Generated by Django 5.2.6 on 2026-09-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0018_seed_brainstorm_prompts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributionuserscore',
            name='memo_raw',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
