# Generated by Django 5.2.6 on 2026-09-05 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0018_store_coach_messages_as_plain_text'),
        ('ai', '0019_memo_raw_decimal'),
    ]

    operations = [
    ]
